# This code is generated by a certain llm
import csv
import json

def csv_to_list_of_dicts(csv_filename):
    # Read the CSV file and convert it into a list of dictionaries
    with open(csv_filename, newline='', encoding='utf-8') as csvfile:
        # DictReader automatically uses the header row as keys
        csvreader = csv.DictReader(csvfile)
        data = []
        
        # Loop through each row in the CSV
        for row in csvreader:
            # Convert fields that are meant to be integers
            for key, value in row.items():
                if value.isdigit():  # Check if the value is an integer
                    row[key] = int(value)  # Convert to integer
            data.append(row)
        
        return data

def save_json(data, json_filename):
    # Save the list of dictionaries as a JSON file
    with open(json_filename, 'w', encoding='utf-8') as jsonfile:
        json.dump(data, jsonfile, ensure_ascii=False, indent=4)


# Example usage
csv_filename = 'Instructions.csv'  # Replace with your CSV file
json_filename = 'Instructions.json'  # The output  JSON file
data = csv_to_list_of_dicts(csv_filename)
save_json(data, json_filename)
